### ISSUE TITLE
源码运行出错

### ISSUE THREAD

**Issue by henson** [hidu/pproxy#16]
试着把代码git clone下来，运行一下，报如下错误：
```
D:\Gworks\src\github.com\hidu\pproxy>go run proxy_main.go
panic: Error parsing builtin CA x509: RSA key missing NULL parameters

goroutine 1 [running]:
github.com/hidu/pproxy/vendor/github.com/hidu/goproxy.init.1()
        D:/Gworks/src/github.com/hidu/pproxy/vendor/github.com/hidu/goproxy/certs.go:10 +0x1ea
github.com/hidu/pproxy/vendor/github.com/hidu/goproxy.init()
        D:/Gworks/src/github.com/hidu/pproxy/vendor/github.com/hidu/goproxy/signer.go:88 +0x2f2
github.com/hidu/pproxy/serve.init()
        D:/Gworks/src/github.com/hidu/pproxy/serve/wsServer.go:179 +0xd7
main.init()
        D:/Gworks/src/github.com/hidu/pproxy/proxy_main.go:52 +0x66
exit status 2
```

按照说明，pproxy.conf里密钥留空会自动使用默认内置的 /res/private/server_key.pem、client_cert.pem，怎么还是报RSA Key missing呢，盼解答

**Comment by zhang5171291** [comment]
我也是同样的错误 
Error parsing builtin CA x509: RSA key missing NULL parameters

**Comment by mairsawang** [comment]
妈的 貌似 搞错了  把demo里的key 复制 过来 就行  ......

**Comment by lchjczw** [comment]
@mairsawang 兄弟，你说的是哪个demo，我这边没找到呢

**Comment by zhuwei** [comment]
同问。。

**Comment by hidu** [comment]
go版本问题，已处理了
